[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173", "http://127.0.0.1:5173"]

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.external]
# Leave empty unless you use Google/GitHub/etc.
