# Generated by Django 5.2.7 on 2025-10-20 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('annual_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fund_share_percent', models.DecimalField(decimal_places=2, default=80, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nhif_number', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('membership_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.membershiptype')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_type', models.CharField(max_length=50)),
                ('date_of_first_visit', models.DateField(blank=True, null=True)),
                ('date_of_discharge', models.DateField(blank=True, null=True)),
                ('total_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('member_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('excluded', models.BooleanField(default=False)),
                ('nhif_number', models.CharField(blank=True, max_length=100, null=True)),
                ('other_insurance', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='medical.member')),
            ],
        ),
    ]
