# Generated by Django 5.2.7 on 2025-11-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_chronicrequest_claimattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
