# Generated by Django 5.2.7 on 2025-11-26 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_member_benefits_from_member_family_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberdependent',
            options={'ordering': ['full_name']},
        ),
        migrations.AddField(
            model_name='memberdependent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='memberdependent',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='memberdependent',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='memberdependent',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='memberdependent',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
