# Generated by Django 5.2.7 on 2025-12-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='claim_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='claim_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='claim_member_idx',
        ),
        migrations.RemoveIndex(
            model_name='claimitem',
            name='claimitem_claim_idx',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='member_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='member_nhif_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_recipient_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_read_date_idx',
        ),
    ]
