# Generated by Django 5.2.7 on 2025-12-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_remove_auditlog_audit_created_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='nhif_number',
            new_name='shif_number',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='nhif_number',
            new_name='shif_number',
        ),
    ]
