# Generated by Django 5.2.7 on 2026-01-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_rename_nhif_number_claim_shif_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('inactive', 'Inactive'), ('lapsed', 'Lapsed')], default='pending', max_length=20),
        ),
    ]
