# Generated by Django 5.2.7 on 2026-02-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0012_auditlog_new_state_auditlog_previous_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="is_trustee_ratified",
            field=models.BooleanField(default=False),
        ),
    ]
