# Generated by Django 5.2.7 on 2026-02-06 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0013_claim_is_trustee_ratified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="claimmeetinglink",
            name="byelaw_reference",
            field=models.CharField(
                blank=True,
                help_text="Mandatory for rejections or limit caps",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="claimreview",
            name="byelaw_reference",
            field=models.CharField(
                blank=True, help_text="e.g. Byelaw §9.1.a", max_length=100, null=True
            ),
        ),
        migrations.CreateModel(
            name="DataAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(default="Claim Review", max_length=255)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medical.claimattachment",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="medical.claim",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accessed_at"],
            },
        ),
    ]
