name: SGSS Backend CI

on:
  push:
    branches: [ main, Backend ]
  pull_request:
    branches: [ main, Backend ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sgss_medical_fund
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/sgss_medical_fund
      SECRET_KEY: test_secret_key
      DEBUG: True

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd Backend
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          cd Backend
          python manage.py migrate

      - name: Run tests
        run: |
          cd Backend
          python manage.py test
